apiVersion: v1
kind: Service
metadata:
  name: demo-kube-service
spec:
  type: NodePort
  ports:
    - port: 8083
      name: http
      targetPort: 8080
  selector:
    app: demo-kube-label
    bar: foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-kube-label
      bar: foo
  template:
    metadata:
      labels:
        app: demo-kube-label
        bar: foo
    spec:
      containers:
        - name: kube-demo-container
          image: kube-demo-image:0.0.2
          ports:
            - containerPort: 8080
