apiVersion: v1
kind: Service
metadata:
  name: demo-kube-service
spec:
  type: NodePort
  ports:
    - port: 8083
      name: http
      targetPort: 8080
  selector:
    app: demo-kube-label
    bar: foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kube-deployment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-kube-label
      bar: foo
      version: 0.0.1
  template:
    metadata:
      labels:
        app: demo-kube-label
        bar: foo
        version: 0.0.1
    spec:
      containers:
        - name: kube-demo-container
          image: kube-demo-image:0.0.1
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kube-deployment-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-kube-label
      bar: foo
      version: 0.0.2
  template:
    metadata:
      labels:
        app: demo-kube-label
        bar: foo
        version: 0.0.2
    spec:
      containers:
        - name: kube-demo-container
          image: kube-demo-image:0.0.2
          ports:
            - containerPort: 8080
